Update of Addon HGTV Mediathek to v.1.1.9
- fixed: Serienordner können unter NEXUS/OMEGA nicht geöffnet werden (AttributeError: 'xbmc.InfoTagVideo' object has no attribute 'setTVShowTitle')