Update of Addon KiKA plus to v.3.4.3
- fixed: Rubrik = Neue Videos kann nicht geöffnet werden (AttributeError: 'NoneType' object has no attribute 'replace')