Update of Addon TLC Mediathek to v.3.2.1
- fixed: Serienordner können unter NEXUS/OMEGA nicht geöffnet werden (AttributeError: 'xbmc.InfoTagVideo' object has no attribute 'setTVShowTitle')