Update of Addon DMAX Mediathek to v.3.2.3
- fixed: Serienordner können unter NEXUS/OMEGA nicht geöffnet werden (AttributeError: 'xbmc.InfoTagVideo' object has no attribute 'setTVShowTitle')