Update of Addon Sportdeutschland.TV to v.2.0.2
- fixed: HTTP Error 422: Unprocessable Entity
- fixed: Übersicht der Videos lässt sich nicht öffnen (KeyError: 'title' oder AttributeError: 'list' object has no attribute 'get')