Update of Addon Skyline LiveCams to v.1.0.4
- fixed: Alle Rubriken können nicht geöffnet werden (Error: 'str' object has no attribute 'get')
- comment * Im Addon angelegte Favoriten sind nicht mehr mit dem jetzigen Addon-Code konform und müssen leider erneut angelegt werden ! *